### ISSUE TITLE
Monolithic build creates string sharing issue in protobuf

### ISSUE THREAD

**Issue by achalshah20** [FloopCZ/tensorflow_cc#131]
When I try to set_visible_device_list through tensorflow API, it updates all the string variables with same value. I know explanation is very confusing. Here are related reference issues and PR.

https://github.com/tensorflow/tensorflow/issues/16291

Proposed solution by member: https://github.com/tensorflow/tensorflow/pull/17767 (I am not sure I understand this though)

**Comment by FloopCZ** [comment]
Well, I am not sure I can be of any help here. The actual need for this whole `tensorflow_cc` project is a good example of how inconvenient is the current design of the TF C++ API build.

You can try to add the line from https://github.com/tensorflow/tensorflow/pull/17767/files if it helps you. If so, we can decide whether to patch the file in this project, since we link protobuf anyway, but I believe it will break some other things.

**Comment by FloopCZ** [comment]
They say that it could be solved by TensorFlow, but nobody is working on it. Or you can solve it yourself if you make a shared lib out of the part of your program that communicates either with TF or with OpenCV. But what I suggest is to apply the change of the referenced pull request itself.
