### ISSUE TITLE
Building for Raspberry Pi 3 B+: File system loop detected

### ISSUE THREAD

**Issue by usptact** [FloopCZ/tensorflow_cc#140]
I am building shared Tensorflow library on RPi3 and got the library built. Btw, it was very important to add extra option `--copt=-DRASPBERRY_PI` to bazel!

The next build steps indicate a problem with installation/copying of the files. It looks like copying is done recursively and directories are being built one inside another. I eventually interrupted the loop:

```bash
Target //tensorflow:libtensorflow_cc.so up-to-date:
  bazel-bin/tensorflow/libtensorflow_cc.so
INFO: Elapsed time: 9976.243s, Critical Path: 1801.85s
INFO: 1653 processes: 1653 local.
INFO: Build completed successfully, 1654 total actions
Replacing links with the copies of their targets.
This may take a while...
find: File system loop detected; ‘./tensorflow/contrib/makefile/gen/protobuf/protobuf’ is part of the same file system loo$
 as ‘./tensorflow/contrib/makefile/gen/protobuf’.
find: File system loop detected; ‘./tensorflow/contrib/makefile/gen/protobuf-host/protobuf’ is part of the same file syste$
 loop as ‘./tensorflow/contrib/makefile/gen/protobuf-host’.
find: File system loop detected; ‘./bazel-tensorflow/external/org_tensorflow/tensorflow/contrib/makefile/gen/protobuf/prot$
buf’ is part of the same file system loop as ‘./bazel-tensorflow/external/org_tensorflow/tensorflow/contrib/makefile/gen/p$
otobuf’.
find: File system loop detected; ‘./bazel-tensorflow/external/org_tensorflow/tensorflow/contrib/makefile/gen/protobuf-host$
protobuf/protobuf/protobuf’ is part of the same file system loop as ‘./bazel-tensorflow/external/org_tensorflow/tensorflow$
contrib/makefile/gen/protobuf-host/protobuf/protobuf’.
find: File system loop detected; ‘./bazel-tensorflow/tensorflow/contrib/makefile/gen/protobuf/protobuf’ is part of the sam$
 file system loop as ‘./bazel-tensorflow/tensorflow/contrib/makefile/gen/protobuf’.
find: File system loop detected; ‘./bazel-tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/protobuf/protobuf/proto$
uf/protobuf/protobuf’ is part of the same file system loop as ‘./bazel-tensorflow/tensorflow/contrib/makefile/gen/protobuf$
host/protobuf/protobuf/protobuf/protobuf’.

^CCMakeFiles/tensorflow_shared.dir/build.make:106: recipe for target 'tensorflow-stamp/tensorflow_shared-configure' failed
make[2]: *** [tensorflow-stamp/tensorflow_shared-configure] Interrupt
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/tensorflow_shared.dir/all' failed
make[1]: *** [CMakeFiles/tensorflow_shared.dir/all] Interrupt
Makefile:127: recipe for target 'all' failed
make: *** [all] Interrupt
```

This makes me wondering whether some important steps were missed. How can I fix this loop?

**Comment by usptact** [comment]
Modifying and re-running cmake results in extra links/folders made by protobuf. Doing a clean cmake/make, the issue is not there.

**Comment by acidtonic** [comment]
Failing to fix this in my opinion was bad coding, filesystem loops can occur outside of the project folder due to details of the how the system was built.

The real bug was failing to handle filesystem loops.

By failing to spend 5 minutes googling for a workaround to the find command, it was easier to hide the problem by telling the OP to not cancel a build without realizing that this could be only one of many triggers of filesystem loops.

On Gentoo python symlinks after upgrades can cause filesystem loops with /usr/include/python3 and /usr/include/python3m. Since building tensorflow eventually calls find without fixing the issue with filesystem loops making find exit with code 1, I can't build tensorflow anymore on Gentoo without either fixing the loop or manually editing the find invocation as reported originally to contain a workaround.

On systems running the Linux kernel, "find -printf %F" no longer produces the wrong answer for files on filesystems that have been remounted elsewhere using "mount --bind". (Savannah bug #14921).

Sad I wasted time with this only to find it *was* reported 2 years prior but not fixed because the symptom of the bug was not "kosher".
