### ISSUE TITLE
Could not use generated target file

### ISSUE THREAD

**Issue by dhgelling** [FloopCZ/tensorflow_cc#209]
When using the generated target file, I got an error when trying to get the TARGET_FILE_DIR in a generator expression, because the generated file was an INTERFACE instead of SHARED target. Apart from that, it is not using the ${_IMPORT_PREFIX} variable, so the generated folder is not relocatable.

I'm not actually sure if this can be fixed while keeping the use of cmake for generating these files, and perhaps that's why it's not doing it at the moment, but I figured I'd raise the issue anyway.

**Comment by FloopCZ** [comment]
I am not sure how to do that actually, since the libraries are generated as `external_project`, not via CMake target. Maybe setting `TARGET_FILE_DIR` manually, but that seems ugly. The same for target property `IMPORT_PREFIX`. But if you have an idea how to improve this, I will gladly welcome a PR! :slightly_smiling_face:

**Comment by FloopCZ** [comment]
Closing for now, feel free to reopen if there are any more questions.
