### ISSUE TITLE
Build configuration

### ISSUE THREAD

**Issue by RDIgor** [FloopCZ/tensorflow_cc#221]
I would like to know the differences of options ALLOW_CUDA and REQUIRE_CUDA?

**1. Why do you need an option REQUIRE_CUDA, if exists ALLOW_CUDA and that means I want to build tensorflow with GPU support?**
**2. I think the build tensorflow with GPU support should be in default mode, so this is more demand, than build on the CPU.**

**Comment by FloopCZ** [comment]
Hi, `ALLOW_CUDA` makes an attempt to find CUDA and if it fails, it falls back to CPU build. `REQUIRE_CUDA` is a stronger option - it also makes an attempt to find CUDA and if it fails, the whole build fails. `ALLOW_CUDA` is the default, so if your OS contains CUDA, it should be auto-detected and the library should be built with CUDA support. I did not want to force CUDA support, because a lot of users use the library in server environment and virtual server environment without a GPU (but sometimes with a lot of CPU power).
