### ISSUE TITLE
Build successful, installation complete, but I get fatal error: tensorflow/core/platform/env.h: No such file or directory when I try to build the example code.

### ISSUE THREAD

**Issue by ranjanisubramanyan** [FloopCZ/tensorflow_cc#237]
I am building this in Ubuntu 18.04.

**Comment by Yasin40** [comment]
I Had same error

**Comment by FloopCZ** [comment]
Can you provide the exact output in order to see the source of the error?
Btw it should work on ubuntu 20.04 as it passes in the CI.

**Comment by michaelnguyen11** [comment]
Same error in Ubuntu 18.04 while building TF 2.3.1. My work around: because "env.h" is in bazel-bin/bin folder, therefore add 2 more lines in /usr/local/lib/cmake/TensorflowCC/TensorflowCCTargets.cmake:
`set_target_properties(TensorflowCC::TensorflowCC PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "/usr/local/include/tensorflow/bazel-bin/tensorflow/include;/usr/local/include/tensorflow/bazel-bin/tensorflow/include/src;**/usr/local/include/tensorflow/bazel-bin/bin/tensorflow/include;/usr/local/include/tensorflow/bazel-bin/bin/tensorflow/include/src**"
  INTERFACE_LINK_LIBRARIES "/usr/local/lib/libtensorflow_cc.so.2;dl;pthread"
)
`

**Comment by FloopCZ** [comment]
What is your Bazel version?

**Comment by michaelnguyen11** [comment]
I used bazel version 3.1.0 as recommendation of tensorflow : https://www.tensorflow.org/install/source#gpu
