### ISSUE TITLE
Failed when make and make install

### ISSUE THREAD

**Issue by MoyanZitto** [FloopCZ/tensorflow_cc#28]
Dear FloopCZ, your work is so amazing and it is reall helpful. But I got some errors when run `make && make install`. Here are what I got in this step:

```
downloading http://mirror.bazel.build/github.com/google/nsync/archive/ad722c76c6e6653f66be2e1f69521b7f7517da55.tar.gz

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
CMakeFiles/tensorflow_base.dir/build.make:106: recipe for target 'tensorflow-stamp/tensorflow_base-configure' failed
make[2]: *** [tensorflow-stamp/tensorflow_base-configure] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/tensorflow_base.dir/all' failed
make[1]: *** [CMakeFiles/tensorflow_base.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

To be honest, I really don't know much about cmake, so I don't know what happened here.
Really need your help...

**Comment by FloopCZ** [comment]
Hi, it seems that your installation is unable to download the mentioned file. The URL seems to be [correct](https://github.com/tensorflow/tensorflow/blob/r1.4/tensorflow/workspace.bzl#L429) though, and I am able to download and extract the file in this moment. There may have been some temporary internet outage, can you try over please?

**Comment by MoyanZitto** [comment]
@FloopCZ 
I have a good news: I can download the file through web browser... so the URL is correct.
And a bad one: still got the same error but with different url:
```
downloading http://mirror.bazel.build/github.com/google/protobuf/archive/b04e5cba356212e4e8c66c61bbe0c3a20537c5b9.tar.gz
```
Can I download these files by hand?

**Comment by FloopCZ** [comment]
That may be possible, but it would require changing some files in the `tensorflow/contrib/makefile` project, I would not do it. :-)
Are you able to download the files via `wget`?
```
wget http://mirror.bazel.build/github.com/google/protobuf/archive/b04e5cba356212e4e8c66c61bbe0c3a20537c5b9.tar.gz
```
Since you have successfully downloaded one of the required files already, this is probably really just a connection issue, please once (or five times) over.

**Comment by MoyanZitto** [comment]
@FloopCZ after trying....many times, I finally successfully make && make install. It's just connection problems. Thank you man, your work is really helpful.

**Comment by dwindy** [comment]
@FloopCZ Hi, is that possible if we manually downloaded these files and placed it in some correct folder?
or i can modify the cmake rules to skipping downloading some files.
because i just met the same problem while downloading eigen. 

the interesting problem is my college's system able to cmake and make.
we are under the same ip.

**Comment by FloopCZ** [comment]
Hi, I don't think there is a straightforward way. The files are downloaded by tensorflow build system.
