### ISSUE TITLE
How to do this on macOS

### ISSUE THREAD

**Issue by PharrellWANG** [FloopCZ/tensorflow_cc#5]
please can you help to build a  version for macOS?

**Comment by FloopCZ** [comment]
Hi, unfortunately, I do not own an Apple machine nor I have a CI set-up for MacOS. Therefore, it will be a little bit hard for me to help you (pull requests welcome).

Have you tried to follow the instructions for Linux shared library? Where has it failed and what error has it produced? Have you installed Bazel and `brew install coreutils`? Have you tried to edit [build_tensorflow.sh](https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/cmake/build_tensorflow.sh) using [MacOS compilation guide](https://www.tensorflow.org/install/install_sources)?

You don't have to bother with CUDA settings, since Google dropped the GPU support for MacOS in TF 1.2.0 anyway.

**Comment by PharrellWANG** [comment]
1. I am using TF1.1.0, and I got a GPU configured with my mac. 
2. I have successfully built TF from source and I have built the libtensorflow_cc.so successfully on  my Mac. 

However,
1. I am not familiar with CMAKE, so it is hard for me to create a similar project for Mac.
2. I am not sure how to use that libtensorflow_cc.so lib on Mac. I have copied it to /usr/local/lib directory but seems it does not work. [Do you have any suggestion about how to use a .so lib on Mac? I have googled but cannot find a good helpful guide.]

**Comment by FloopCZ** [comment]
`tensorflow_cc.so` is not the only thing you need. There are plenty of headers and directories you have to include when compiling your code that uses the TF C++ API. That is why this project uses CMake - to do this automatically for you.

If you _really_ want to use `tensorflow_cc.so` without the help of this project, you have two options. 

1) Build your code using Bazel as described in the [official guide](https://www.tensorflow.org/api_guides/cc/guide). Your code has to be placed inside the tensorflow repository hierarchy.

2) Build your code manually. See [this StackOverflow answer](https://stackoverflow.com/questions/42898577/list-of-headers-to-use-tensorflow-c-api-using-libtensorflow-cc-so/44625673#44625673) that lists the directories you have to include (using `-I` flag in your compiler). Also don't forget to link `-lpthread` and `-ldl`.

However, I would still suggest to use this project instead, since it becomes a lot easier. Since you have built `tensorflow_cc.so` once already, your system must have all the dependencies installed. Therefore, you should be able to follow the instructions beginning from step 2). Just install CMake and try to follow the commands used for building the shared library. You don't have to be familiar with CMake, copy paste and uncommenting a few lines should be sufficient.

One more thing, if you want GPU support on macOS, you should change [this line](https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/cmake/TensorflowBase.cmake#L6) to `GIT_TAG v1.1.0`. I cannot guarantee it will work then, however.

**Comment by gilbertfrancois** [comment]
I've compiled the tensorflow_cc.so libs and gathered the necessary headers for developing your own C++ programs with tensorflow on macOS. I made a little blog post from it. However, it is not really a clean way of doing it. 
[http://www.blitzblit.com/2017/06/11/creating-tensorflow-c-headers-and-libraries/](http://www.blitzblit.com/2017/06/11/creating-tensorflow-c-headers-and-libraries/)

**Comment by PharrellWANG** [comment]
@FloopCZ 
Great, thank you so much. I have followed your instructions and your example is actually working now. 
I would like to try for my own project. 

And I have one question here:
You mentioned in your last reply for me that "You don't have to be familiar with CMake".
But to build my own project, I still need to configure a CMakelist.txt by myself, is it? There's no way to use the TF C++ API without CMake under the circumstance that I used your project here, is it?

**Comment by PharrellWANG** [comment]
@gilbertfrancois 
I have tried your suggestions. But since I am not familiar with CMake, I stopped at the last step in your post. Thank you for your info. I think I shall spend some time learning CMake.

**Comment by FloopCZ** [comment]
Glad it worked!

And yes, you are right. To build your own project, you have to configure `CMakeLists.txt` by yourself, or with the help of your IDE. If you don't want to use CMake at all (which I would not recommend), you can do the following. Instead of building the example using `make` command, run `VERBOSE=1 make`. Then you will be provided with the exact command that is run to build the example. Then, you can use the compiler flags for your own project.

**Comment by FloopCZ** [comment]
> You mentioned in your last reply for me that "You don't have to be familiar with CMake".
But to build my own project, I still need to configure a CMakelist.txt by myself, is it? There's no way to use the TF C++ API without CMake under the circumstance that I used your project here, is it?

See my previous reply that describes how to extract the raw compiler command.

> And I haven't verified that whether my previous tensorflow installation of python3 still working or not. Do you have a quick answer that can tell me it is not affected by using your project? Thank you.
(I think probably not affected. since your are not building //tensorflow/tools/pip_package:build_pip_package)

Exactly as you say, your original python TF is not affected.

**Comment by formath** [comment]
@FloopCZ I have this problem when linking my custom prediction cpp on macOS. Do you have any suggestions? Thanks.  https://github.com/tensorflow/tensorflow/issues/13306
