### ISSUE TITLE
about 400MB of shared library libtensorflow_cc.so

### ISSUE THREAD

**Issue by bitatomcat** [FloopCZ/tensorflow_cc#52]
399590304 2月   7 18:02 libtensorflow_cc.so. stripped version.
As a reference, https://github.com/cjweeks/tensorflow-cmake   generates about 180MB tensorflow_cc.so.

**Comment by FloopCZ** [comment]
If you want a smaller shared library, I recommend you to take a look at the [build file](
https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/cmake/build_tensorflow.sh). You can disable many features, such as [Intel MKL](https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/cmake/build_tensorflow.sh#L13), that can considerably enlarge the library.

Furthermore, you can only build the [CUDA compute capabilities](https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/cmake/build_tensorflow.sh#L54) of your GPU instead of building four different ones. Take a look at the official [CUDA capabilities](https://developer.nvidia.com/cuda-gpus) website to find what capabilities does your GPU support.
